### ISSUE TITLE
add ability to target dimensions / file size / vertex count

### ISSUE THREAD

**Issue by nvkelso** [mbloch/mapshaper#103]
Large input files (filesize / vertex count / properties) load slowly over the web, so it would be useful to have a "lite" or "preview" version that meets a 2 megabyte (customizable) threshold. 

Mapshaper currently offers the ability to simplify to a percent or original or spatial sampling resolution. But that approach means I need to customize the params per file to achieve the desired amount of simplification. Instead I'd like something that can run automatically on the command line that either does **not** generalizing the file if it's already under the size threshold, or generalizes the input a variable amount to achieve the output threshold.

I would like to use this to generate "lite" versions of Natural Earth that could be used in an "[atlas](https://github.com/mbostock/us-atlas)" context targeting [Leaflet](http://leafletjs.com) &/or [D3.js](http://d3js.org). And I would use it in Mapzen's [Who's On First](https://mapzen.com/blog/who-s-on-first) gazetteer project for previewing records in the [Spelunker](http://whosonfirst.mapzen.com/spelunker/). 

I'd like a new function that simplifies until the maximum number of vertices is met (whatever % or sample distance param that is). 

Alternatively, maximum file size could also be supported (but that means different things for Shapefile versus GeoJSON, and additional options in GeoJSON like pruning whitespace and truncating float precision would need to be considered).

**Comment by mbloch** [comment]
@nvkelso, we could add the kind of parameter that  you're proposing...  first I'd like your  thoughts on an alternative that might also work for your use case. At least it could work for the gazetteer, where you're generating maps at a range of scales but with a consistent display size.

I've been thinking about a way of specifying the amount of simplification based on the display size of the map that the user intends to make.

The syntax might look like this: `-simplify resolution=1000x1000`.

The `resolution` option would pick a simplification threshold so that, if the data were scaled to fit inside a rectangle of a given size (1000x1000 in the example above), details smaller than about a single unit would be removed.

Some examples:

If you wanted to make a print map at 10 x 8 inches and remove details smaller than 1/300in, you could specify `resolution=3000x2400` (because 10 * 300 = 3,000 and 8 * 300 = 2,400).

If you wanted to make a 1000x500 pixel slippy map for the web, and you wanted pixel-level detail at 16x zoom (i.e. zooming  four levels beyond the level where the content fills the map), you would specify `resolution=16000x8000`  (because 1000 * 16 = 16000  and  500 * 16 = 8,000).

There are some caveats with this method, which I think can be overcome:

If you use the size of the map viewport to calculate resolution, you're in effect assuming that the data will either fill the entire height or width of the map, which is generally not the case.

Another caveat: We need a slightly different method for calculating a simplification threshold from output resolution if the data is unprojected.

**Comment by nvkelso** [comment]
@mbloch I really dig this alternative approach! I think it could also work for the weird Natural Earth "lite" use case, too.

**Comment by mbloch** [comment]
Cool, I think this will be useful to a bunch of people. I'll let you know when it's ready to test. Should be within a week.

**Comment by nvkelso** [comment]
Awesome, thanks for having a look :)

**Comment by mbloch** [comment]
I just published v0.3.11, which includes the `resolution=` option that I introduced up above. It may need some tweaking, so please leave some feedback.

When using planar simplification (when the data has projected coordinates or the `-simplify cartesian` option is used), the `resolution` parameter works basically as described above.

When using spherical simplification, I calculate the simplification interval by first converting the lat-long bounding box of the data to a rectangle in units of meters. The width of the rectangle is calculated using the length of the arc that intersects the center of the bounding box and runs from one side of the bbox to the other at a constant latitude. The height of the rectangle is calculated using the length of the arc running through the center of the bounding box at a constant longitude. This provides a crude approximation of the extent of the data after it is projected. Maybe I should draw a diagram to clarify how this works...

**Comment by mbloch** [comment]
I've used the `resolution=` option several times, and it seems to work well, so I'm closing this issue.
