### ISSUE TITLE
Make runParsedCommands public

### ISSUE THREAD

**Issue by mijamo** [mbloch/mapshaper#119]
Hello,

I am using mapshaper for quite a lot of operations and at some point it becomes cleaner to use parsed commands than building really huge strings (I frequently have 10 commands chained with many arguments that need to come from variables).

In mapshaper source code, the perfect function to do that is runParsedCommands, but unfortunately it is not available by default, we only have runCommand. 

Is there a reason why runParsedCommands is not public ?

A more extended doc on the options names to build the commands would also be good. As it is quite a huge task I could participate to build it if it can help.

**Comment by mbloch** [comment]
Let's think about the best way to do this... I see documentation as the biggest obstacle.

I'd rather not have to maintain two sets of documentation (one for end-users and one for developers). Ideally, developers could learn everything they need to know about building a parsed command object from the [command reference](https://github.com/mbloch/mapshaper/wiki/Command-Reference). This could work if the rules for converting command line arguments to JavaScript objects were simple and automatic.

Currently, some of the conversions are already simple and automatic. For example, comma-separated lists get converted to arrays of strings, and numerical strings get converted to numbers.

Other conversions are not automatic. The main culprit is unnamed arguments like `10%` in `-simplify 10%`, which gets converted to {pct: 0.1}, or `country.shp` in `-i country.shp`, which gets converted to `{files: ["country.shp"]}`.

Option A for dealing with unnamed arguments is to get rid of them, so instead of `-simplify 10%` you would use something like `-simplify pct=10` on the command line. I like the convenience of the unnamed arguments, so I'm not in favor of this.

Option B is to stop converting unnamed arguments to named arguments. So instead of converting `-i country.shp` to `{files: ["country.shp"]}`, the parsed command would contain something like `{_:["country.shp"]}`.

Option C would be to treat each unnamed argument as an alias for a named argument. I would update the command reference to give the corresponding name for each unnamed argument. This should give enough information for developers to build JavaScript objects for each command.

Do you have a preference? I'm currently leaning towards C.

**Comment by nvkelso** [comment]
C.

**Comment by mijamo** [comment]
I agree with C.

There is also option D in my opinion which would be to make named component correspond to the `<files>` arguments currently in the documentation.

For instance, for `-i` it is quite straighforward that one should use `files `because the doc says `<files>` but for `-simplify` one would like to use `options: {percentage: 0.4}` because the doc says `<percentage>` (and well `percentage `is more intuitive that `pct`). So the option D would be to always have it possible to use the name inside `<>` as an argument. It is actually the case in most of the functions today already.

Then it should just be written in the doc to use this scheme for programmatical use (with some examples).

I provided the D idea because that is what I tried intuitively at first when I started to use runParsedCommands before going into the actual code.

The problem with this would be how to handle the fact that many options have several possibilities for the inline argument (`file|directory` for instance), and that it needs some internal changes and not only the doc so it's probably more work, but I still wanted to point this option.

**Comment by mbloch** [comment]
Option D from @mijamo  could work, I think. It's just a question of finding names for each of the &lt;option&gt; annotations that can also be used as property names in a JS object.

Below are some examples. Option C would list the aliases explicitly, as I've done below. That seems a bit redundant, so I'm leaning towards @mijamo's suggestion.

#### -o (output)
`<file>|<directory>|-` Name of output file or directory. Use `-` to export TopoJSON or GeoJSON to stdout.
`file=`  Alias for `<file>`.
`directory=`  Alias for `<directory>`.

#### -join
Instead of `<file|layer>`:
`<source>`  File or layer containing data records to join.
`source=`  Alias for `<source>`.

#### -rename-layers
Instead of `<name(s)>`:
`<names>`  One or more layer names (comma-separated).
`names=` Alias for `<names>`.

#### -split-on-grid
Instead of `<cols,rows>`:
`<grid>`  Size of the grid in cols,rows (Example: `-split-on-grid 12,10`)
`grid=` Alias for `<grid>`.

**Comment by mbloch** [comment]
@mijamo a quick update: I'm planning to include this change when I jump to version `0.4.0`, along with several other changes that will likely catch people by surprise if I slip them into a patch-level release.

**Comment by mijamo** [comment]
I think this is great!

Do not hesitate to tell if I can help in any way for the documentation.

**Comment by mbloch** [comment]
Sorry this took a while...  I just released v0.4, which addresses two of the issues that we talked about above.

First, instead of making `runParsedCommands()` public, I decided to change `runCommands()` and `applyCommands()` to accept arrays of parsed commands as an alternative to strings of command line arguments.

Second, I tried to harmonize the parameter names used in the documentation with the names of command options. Some examples:
* `-simplify` takes a `percentage` option (instead of `pct`), and the inline argument is documented as `<percentage>`.
* `-o` takes either a `directory` or a `file` option, and it is documented as `<file|directory|->`.
* `-clip` and `-erase` both take a `source` option, and their inline argument is listed as `<source>` (instead of `<file|layer>`).
* `-filter-fields` takes a `fields` option, which is listed as `<fields>` (before it was `<field(s)>`).

I made a few other similar changes.
