### ISSUE TITLE
Show a base map in the GUI

### ISSUE THREAD

**Issue by danvk** [mbloch/mapshaper#126]
e.g. mapbox, OSM, etc. Similar to how geojson.io works.

**Comment by mbloch** [comment]
In order to show a tiled basemap for datasets that do not use the WGS84 coordinate reference system, mapshaper would need to add a library for projections and datum transformations. Then the user's data would have to be projected to "web Mercator" for display. It could be done, but I don't have a personal need for this feature, so I'm biased against working on it.

My preference is to let users go to geojson.io to display their WGS84 data on a raster basemap. I'm open to reconsidering, though, if there's a strong case for adding the feature.

**Comment by mg262** [comment]
mapshaper is very nice, but the slider feature for simplification would be a lot more useful if one could display a base map. Without that it's hard to see what is being lost.  

If the projections are an issue, you could display the base map only in the case where input is WGS84.

**Comment by mbloch** [comment]
This feature is more feasible now that mapshaper has better support for projections and datum transformations... just checking in to say that I'll be looking into adding this feature.

**Comment by ericjarvies** [comment]
It would be nice to be able to add some GeoServer WMS links and have those manifest into toggle-able layers.

**Comment by kzka90** [comment]
Has anyone done this? I'm very interested on achieving it.

**Comment by kzka90** [comment]
> In order to show a tiled basemap for datasets that do not use the WGS84 coordinate reference system, mapshaper would need to add a library for projections and datum transformations. Then the user's data would have to be projected to "web Mercator" for display. It could be done, but I don't have a personal need for this feature, so I'm biased against working on it.
> 
> My preference is to let users go to geojson.io to display their WGS84 data on a raster basemap. I'm open to reconsidering, though, if there's a strong case for adding the feature.

Can you elaborate a little bit more what needs to be done for this, please. I'm really looking forward to place a map below the SVGs.

**Comment by DarinMacRae** [comment]
I just found MapShaper today and am impressed by how easy it is to use. However, without a base map it's usefulness is limited. I see others have expressed an interest in this over the years. Are there any plans to add support for this?

**Comment by ndrezn** [comment]
Adding additional support for this feature! Being able to toggle a base map on or off would be incredibly powerful.

**Comment by mbloch** [comment]
I added a basemap option to the web UI, it's live on mapshaper.org:
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/1232222/159831151-92dd695a-5488-4e7b-93bc-6fb05a928306.png">

**Comment by ThomasG77** [comment]
Seems the added layer stay below when clicking on the basemap. See demo

![issue-mapshaper-basemap-optimized](https://user-images.githubusercontent.com/642120/159920657-ae64f6cf-4609-4438-ae0e-a9aeb0671ec4.gif)

**Comment by mbloch** [comment]
@ThomasG77 I see what's happening...  the projection function is throwing an error when it encounters an unprojectable point (possibly latitude -90 in the Antarctica polygon). You can see that Japan and the Philippines are getting displayed in your test. I'll work on a fix... thanks for reporting :)

**Comment by mbloch** [comment]
Another work-in-progress item: I'm planning to remove the restriction that only WGS84 and Web Mercator data can be displayed on a basemap. First I need to add appropriate error detection and messaging when mapshaper can't reproject a particular dataset. For example, mapshaper doesn't support grid transformations, so it can't reproject data from some datums, like NAD27.

**Comment by ThomasG77** [comment]
As I do not see extent validity for projections in your https://github.com/mbloch/mapshaper-proj, you may want to get extent with infos from a package like https://npm.io/package/epsg-index

**Comment by mbloch** [comment]
The latest release addresses the problem where the basemap does not initially display when the data layer extends beyond the viewable extent of the Mapbox map (The map starts zoomed-in to a valid Mapbox extent).

This release also removes the WGS84/WebMercator restriction on using the basemap feature. Clamping latitudes before projecting to WebMercator for display seems to work well, I'm going to keep that in there. Features containing unprojectable coordinates will not display, but other features in the same layer should be displayed.

Thanks for testing and helping to catch bugs! There will be more bugs related to basemaps, i'm sure.

**Comment by mbloch** [comment]
The basemap feature seems to work reasonably well, so i'm closing this. @ThomasG77 I'll think about your suggestion to add an opacity control. My thought would be to have some kind of toggle to switch between a faded-back or hidden basemap, so the user can see their data clearly, and the full basemap, so the basemap context is clearly visible. For toggling, a button or keyboard shortcut might be more convenient than the familiar opacity slider. Feel free to add a new issue if you have a specific design in mind.

**Comment by ManuelUrrutia** [comment]
Is there a way to inform users of the "local" version of mapshaper (aka mapshaper-gui) that the basemap "feature" is not available when locally run? Maybe I am too dense, but it took me a while to realize that, even if I use the latest version (0.6.5) locally, the basemap will not be available because it requires the use of a Mapbox key that allows access to the maps as long as it is run from the Web GUI. Is there an open-source set of maps that could be used instead? I naively thought that since "©OpenStreeMap" is displayed on the lower right-hand corner that these maps could be used locally without an API key instead of Mapbox's services. No idea how much of a bag of hurt implementing that would be. And, yes, beggars can't be choosy.  :-)  )

**Comment by mbloch** [comment]
I just updated mapshaper to let people running mapbox-gui on localhost to use the basemaps.

**Comment by ManuelUrrutia** [comment]
Thank you for the quick action/response. Much appreciated.

I have updated mapshaper via npm (npm install -g mapshaper) and my installation shows it is now version 0.6.6. However, running mapshaper-gui does not present the Basemap menu item. Inspection of the contents of the mapshaper/www folder reveal that basemap.js is absent and the . Something seems to have gone wrong somewhere. I hope it is easy to fix.

Again, appreciate your kindness in your attention to this request.

**Comment by mbloch** [comment]
Thanks for the heads-up... I needed to add `basemap.js` to the npm bundle (just checking it in to the repo was not enough). Just repubbed. You can also just drop this file into `www/` https://github.com/mbloch/mapshaper/blob/master/www/basemap.js

**Comment by ManuelUrrutia** [comment]
It works now. Thank you, thank you, thank you!

**Comment by ManuelUrrutia** [comment]
Another note: basemaps shown on the screen will not be included when saving to an SVG file. Is this because the basemap is not a "true" layer (that is, it cannot be manipulated by the user and is not on the layer list)?  Yes, it is very useful to see the "real world" geography being mapped on the screen, but images without the basemap are not as useful. I realize this further "refinement" of including the basemap on images might be another bag of hurt. Upping the ante, can the basemap information even be included in shape or json files so that they be further processed off-line, that is, without access to Mapbox's server?  If this is possible, great. If not, I guess that users will have to wait for further development (if ever) down the road. Again, thank you very much for your (and others!) work on this. Mapshaper is an extremely useful and valuable tool.

**Comment by mbloch** [comment]
Unfortunately, Mapbox's TOS prohibits exporting basemap data, or even tracing it.  Even if it was permitted, Mapbox's API does not support exporting to SVG. (I've been told they're working on SVG export).

**Comment by ManuelUrrutia** [comment]
That's what I suspected: a bag of hurt as well as legal impediments. Thank you for that confirmation.

Incidentally, while working on a workaround (namely, taking a snapshot of the screen), I noticed that the SVG file, after being "placed" into Adobe Illustrator, needs to be manually "stretched" to have the aspect ratio of the screen snapshot. To my admittedly not well-informed eye, it seems as if the projection used on the screen is not used in the SVG.

**Comment by mbloch** [comment]
You should project your data using mapshaper's `-proj` command if you're exporting to SVG. If you want to use "Web Mercator" (same as Mapbox uses) then type `-proj webmercator` in the console.

**Comment by ManuelUrrutia** [comment]
Ah, thank you for that bit of information. 

For the benefit of those who may come upon this issue, I should note that the projection included in the Geojson file I am using is WGS84 (info reports "CRS: +proj=longlat +datum=WGS84"). From your advice, the screen uses a webmercator projection and thus it has to be defined "by hand" prior to exporting to SVG if there is a WYSIWYG expectation when putting the SVG into print.

Again, thank you for sharing that and helping dispel my ignorance (ars longa, vita brevis).
