### ISSUE TITLE
Add path id attribute when exporting to svg

### ISSUE THREAD

**Issue by nlemsieh** [mbloch/mapshaper#132]
It possible to add path id attribute when exporting to svg file?

Thanks

**Comment by mbloch** [comment]
When exporting to SVG, Mapshaper wraps each feature in a <g> tag. Ids get added to the <g> elements, instead of to <path> elements. There are a few ways to add ids:

1. If you imported GeoJSON or TopoJSON features with ids, the SVG output will preserve the original ids.
2. If you use the `id-field=` command line option when exporting, the SVG output will contain ids.
3. If there is a data field named `FID`, the SVG output will use these values as ids.

Does one of these methods work for you?

**Comment by nlemsieh** [comment]
Yes , the method 2 works for me, because I have a custom id name.

Thank you

**Comment by mbloch** [comment]
I've been developing mapshaper as a production tool rather than as a geoprocessing library with an API, so an API is a low priority for me.

It is possible to call mapshaper functions from a JS application; there's a wiki page about that:
https://github.com/mbloch/mapshaper/wiki/Using-mapshaper-programmatically

If you have some ideas about improving API support, I'd like to hear them.

**Comment by gagan-bansal** [comment]
@nlemsieh For this particular purpose you can use [geojson2svg](https://github.com/gagan-bansal/geojson2svg) as API in browser or node.js.

@mbloch If you feel its cross posting then I can remove the comment.

**Comment by megharajdeepak** [comment]
Can we export multiple IDs to svg?

**Comment by mbloch** [comment]
Closing this issue -- mapshaper currently supports adding id attributes to SVG paths.
