### ISSUE TITLE
"-o format=geojson" is outputting to .json instead of .geojson

### ISSUE THREAD

**Issue by ericjarvies** [mbloch/mapshaper#142]
When using the **-o format=** option with the **geojson** flag, the subsequent output files are named *.json instead of *.geojson.

**Comment by mbloch** [comment]
Both `.json` and `.geojson` are listed as possible file extensions in the latest spec (https://tools.ietf.org/html/rfc7946). Mapshaper uses `.json` as the default file extension for both TopoJSON and GeoJSON-formatted files. I'll consider changing this behavior, could you explain why you prefer `.geojson`?

**Comment by ericjarvies** [comment]
Matthew,

When I output attributes-only whilst using mapshaper, it makes logical sense that the files are named using the .json extension.

However, when I output spatial data (whether attributes are included or **not**), it does **not** seem logical to use the .json extension, instead, it seems logical to use the .geojson extension.

Additionally, most spatial apps -by default- will open a .geojson file, whereas they will not open a .json file.  The same applies to most services (Git -for example- will display .geojson files atop a map canvas).  Conversely, a cell editor app will open a .json file but not a .geojson file.

Sure, one can manually associate file extensions with specific apps... but that is just one more thing.  Likewise, one can also -batch- rename the files after having used mapshaper to generate them (in batch), but that seems to go contrary to the very nature of mapshaper and what it provides the user in terms of easy in & out capability.

Eric

**Comment by mbloch** [comment]
Hi,

I think you're overstating the case for using `.geojson` instead of `.json`.

* The geospatial apps that I use the most (e.g. QGIS and ogr2ogr) can all open `.json` files just fine.
* GitHub knows how to render GeoJSON and TopoJSON files that have a `.json` extension (see https://help.github.com/articles/mapping-geojson-files-on-github/).

Still, I understand that some people prefer  `.geojson` to `.json`. Perhaps there's a simple way to specify what file extension to use, in cases where you are outputting a bunch of files. For example: `-o format=geojson ext=geojson`.

I'd also be ok with switching to `.geojson` and `.topojson` as the default, if that's what most people want. I'd like a few more people to weigh in on this before making the change.

**Comment by ericjarvies** [comment]
Hello,

Yes, perhaps (_overstating_).

From my own use-case scenario perspective, I would very much appreciate being able to output to either;
**.topojson**
**.geojson**
**.json**

To simply avoid having to add an additional step afterwards of changing all the file extensions.

Of course, it boils down to whether or not it makes sense for you to add this to mapshaper... I for one think it does, hopefully some other users will chime in and give their opinion 👍 

Eric

**Comment by nvkelso** [comment]
+1 for file extension options.

For Mapzen vector tile we end up using .json for GeoJSON files, and
.topojson for TopoJSON variants of the same tile geography, for instance.
It's good to have options :)

**Comment by mbloch** [comment]
I added an `-o extension=` option, which lets you set the extension of TopoJSON and GeoJSON output files according to your own preference, in cases when you don't specify the output filename directly (e.g., if you're processing an entire directory of files with a single command).

I slightly prefer `.geojson` and `.topojson` to `.json` as default file extensions, but I'm leaving the default as `.json` for the time being, since it is a valid extension for both GeoJSON and TopoJSON file types (i.e. it is not wrong), and changing the default might cause problems for some users (e.g. it might break scripts or Makefiles).
