### ISSUE TITLE
Feature Request: Open a file from URL

### ISSUE THREAD

**Issue by thejeshgn** [mbloch/mapshaper#145]
It would be great if we could open a map file directly from a URL. As of now I download it and then upload it mapshaper.

For example: http://www.mapshaper.org/?url=[real url of json or shapefile] 

This helps also to send someone a map link directly.

**Comment by mbloch** [comment]
I added this feature to the latest release (it has already been requested several times). Loading files directly from a different domain requires that the remote server be configured for cross-domain resource sharing (CORS). This is usually not the case, so I suspect that this feature will not be very useful in practice.

To load one or more files from online sources, you would add the `?files=` query string, followed by a comma-separated list of urls, like this:
`http://mapshaper.org/?files=http://www2.census.gov/geo/tiger/GENZ2015/shp/cb_2015_us_cd114_5m.zip`

But since the Census department server is not configured for this, you get an error message:

![image](https://cloud.githubusercontent.com/assets/1232222/20469592/0e38ee1e-af6f-11e6-9c7a-628e2ea47121.png)

**Comment by thejeshgn** [comment]
Thank you. Its very useful for @datameet community.

Here is an example link. If someone wants to try

http://mapshaper.org/?files=https://cdn.rawgit.com/datameet/Municipal_Spatial_Data/1866f495888eaeabd75bbe575bd40902b5ee63cf/Bangalore/BBMP.GeoJSON

**Comment by mbloch** [comment]
Looks good! For previewing GeoJSON datasets, you may find that geojson.io is more useful than mapshaper, since it overlays your data on a basemap. Here's a link to the same dataset on geojson.io:
http://geojson.io/#data=data:text/x-url,https://cdn.rawgit.com/datameet/Municipal_Spatial_Data/1866f495888eaeabd75bbe575bd40902b5ee63cf/Bangalore/BBMP.GeoJSON

**Comment by thejeshgn** [comment]
Thank you @mbloch 

- @datameet community is mostly made up of non tech people
- Quite a few use geojson.io
- But a lot of them in the community need a tool to simplify, export to other formats etc. We use mapshaper a lot for that. I usually send them the link and then an how-to video I made. So this feature makes it much more user friendly, specially when we send links.

Thanks a ton for taking time to create mapshaper.

**Comment by mbloch** [comment]
I'm glad this feature will be useful... thanks for requesting it :)
