### ISSUE TITLE
Feature request: orthogonalize

### ISSUE THREAD

**Issue by waissbluth** [mbloch/mapshaper#162]
A way to make shapes corners' straight, a la OSM's iD `orthogonalize()`: 
https://github.com/openstreetmap/iD/blob/master/modules/actions/orthogonalize.js

Which, in turn, is based on https://github.com/openstreetmap/potlatch2/blob/master/net/systemeD/potlatch2/tools/Quadrilateralise.as

This would be very useful.

**Comment by mbloch** [comment]
Hi, could you explain a bit about what this feature would be good for? Is it for simplifying building outlines?

**Comment by waissbluth** [comment]
Yes, for example. It is a very handy feature in iD when drawing or editing building outlines or any other set of mostly [rectilinear polygons](https://en.wikipedia.org/wiki/Rectilinear_polygon). The algorithm straightens any corners that are _almost_ right (e.g. between 78 and 102º in `orthogonalize.js`)

**Comment by mbloch** [comment]
This isn't a feature that I would have time to work on (I've been focusing on functionality that my colleagues and I could use in our work).

Currently, it takes a very detailed understanding of mapshaper's internal plumbing in order to add a new command. It would be nice to have some kind of plugin or module api, so users could write their own commands and publish them as Node modules, using npm. I just added a new issue about this (#169).
