### ISSUE TITLE
Unable to install getting errors

### ISSUE THREAD

**Issue by shreyesgithub** [mbloch/mapshaper#164]
I am executing the command with super user permission even then i am getting the following error. Can someone please help me here

Shreyess-MacBook-Pro:~ shivshreyes$ npm install  https://github.com/mbloch/mapshaper.git
/Users/shivshreyes
└─┬ mapshaper@0.4.2  (git+https://github.com/mbloch/mapshaper.git#1154166267f11a8d26065933835c07b4753bf7f7)
  ├─┬ d3-dsv@1.0.3 
  │ └─┬ commander@2.9.0 
  │   └── graceful-readlink@1.0.1 
  ├── iconv-lite@0.4.15 
  ├─┬ mproj@0.0.5 
  │ └── geographiclib@1.46.0 
  ├── open@0.0.5 
  ├─┬ optimist@0.6.1 
  │ ├── minimist@0.0.10 
  │ └── wordwrap@0.0.3 
  ├── rbush@1.4.3 
  └── rw@1.3.3 

npm WARN enoent ENOENT: no such file or directory, open '/Users/shivshreyes/package.json'
npm WARN shivshreyes No description
npm WARN shivshreyes No repository field.
npm WARN shivshreyes No README data
npm WARN shivshreyes No license field.
Shreyess-MacBook-Pro:~ shivshreyes$

**Comment by mbloch** [comment]
Looking at these console messages, it appears that `npm` successfully installed mapshaper in your `~/node_modules/` directory.

The WARN messages are warnings that `npm` prints when you are installing a package locally (without the `-g` flag) and a `package.json` file is not present.

I think that `npm` has been printing these warning messages since Node v.5.

If you want to install the latest release version of mapshaper, you can try this command:
`npm install -g mapshaper`

If you need superuser permissions to install to `/usr/local`, you would go: `sudo npm install -g mapshaper`
