### ISSUE TITLE
combine-files don't output projection

### ISSUE THREAD

**Issue by pyrog** [mbloch/mapshaper#166]
```
$ mapshaper -i file1.shp file2.shp combine-files -merge-layers -o merged-file.shp
Wrote data/merged-file.shp
Wrote data/merged-file.shx
Wrote data/merged-file.dbf
```
mapshaper "forgot" to write projection file 😞 

```
$ mapshaper -i file1.shp combine-files -merge-layers -o single-file.shp
Wrote data/single-file.shp
Wrote data/single-file.shx
Wrote data/single-file.dbf
Wrote data/single-file.prj
```
work fine 😄 

Notes:
* both shape files have the same projection.
* same issue with geojson format (except that one have an crs null property, and the other haven't it)

single-file.geojson
```json
{"type":"FeatureCollection","features":[
…
]}
```

merged-file.geosjon
```json
{"type":"FeatureCollection","crs":null,"features":[
…
]}
```

**Comment by mbloch** [comment]
I just published v0.4.5, which retains the .prj file when multiple Shapefiles are combined.

Mapshaper currently is unable to generate .prj files, it can only copy them from an input source. So for some combinations of commands, mapshaper will still output Shapefiles that are missing a .prj file. This will happen if you (re)project using the `-proj` command, or if you convert GeoJSON to Shapefile. I'm working on .prj generation, hoping to add that feature in a couple of weeks.

About the "crs:null" in some GeoJSON files, which you pointed out.... According to the 2008 GeoJSON spec, if a GeoJSON file has no "crs" member, the coordinate system is assumed to be WGS84, and if the "crs" member is null, no assumption can be made ([reference](http://geojson.org/geojson-spec.html#named-crs)). Mapshaper doesn't know how to generate GeoJSON "crs" data, so you're generally going to get no "crs" or a null "crs" -- and, as you noticed, mapshaper is not very consistent about adding a null "crs" to non-WGS84 datasets.

To complicate matters, there's an updated version of the GeoJSON spec, "RFC 7946," which eliminates the "crs" member and says that all GeoJSON files use WGS84, "However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted" ([reference](https://tools.ietf.org/html/rfc7946#section-4)).

If mapshaper's inconsistent treatment of "crs" is causing problems on your end, I'll consider a quick fix... otherwise, I'm inclined to let it slide until I figure out how to handle the incompatibility between the two GeoJSON versions.

**Comment by pyrog** [comment]
> I just published v0.4.5, which retains the .prj file when multiple Shapefiles are combined.

Thanks 😄 

> I'm working on .prj generation, hoping to add that feature in a couple of weeks.

Good news

> Mapshaper doesn't know how to generate GeoJSON "crs" data

Mapshaper could output a "comment" string containing the .prj… until you generate the crs field ?

> According to the 2008 GeoJSON spec, if a GeoJSON file has no "crs" member, the coordinate system is assumed to be WGS84
[…]
as you noticed, mapshaper is not very consistent about adding a null "crs" to non-WGS84 datasets.

To be consistent, you could remove the "crs" member to all GeoJSON files (in theses examples).
And (If I well understood you), to comply to the specs, you could re project objects to WGS84 if input files have a projection.

> If mapshaper's inconsistent treatment of "crs" is causing problems on your end
No 😅

Thank you

**Comment by pyrog** [comment]
What hapened when `file1.shp` and `file2.shp` have a different projection ?
Does `merged-file.shp` will have a projection ?

My real merged files, 3 of them the same projection and the last file have a similar (but different ??) projection.

`PROJCS["RGF_1993_Lambert_93",GEOGCS["GCS_RGF_1993",DATUM["D_RGF_1993",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",700000.0],PARAMETER["False_Northing",6600000.0],PARAMETER["Central_Meridian",3.0],PARAMETER["Standard_Parallel_1",44.0],PARAMETER["Standard_Parallel_2",49.0],PARAMETER["Latitude_Of_Origin",46.5],UNIT["Meter",1.0]]`

`PROJCS["RGF93 / Lambert-93",GEOGCS["RGF93",DATUM["Reseau Geodesique Francais 1993 (EPSG ID 6171)",SPHEROID["GRS 1980 (EPSG ID 7019)",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",700000.0],PARAMETER["False_Northing",6600000.0],PARAMETER["Central_Meridian",3.0],PARAMETER["Standard_Parallel_1",49.0],PARAMETER["Standard_Parallel_2",44.0],PARAMETER["Latitude_Of_Origin",46.5],UNIT["Meter",1.0]]
`

**Comment by mbloch** [comment]
Mapshaper will let you combine multiple projected datasets, even if the projections are incompatible. In such cases, the first .prj file is retained. But you'll get an error if you try to combine a projected and an unprojected dataset.

Once mapshaper's projection functionality is more mature, I'll consider automatically reprojecting input datasets.

**Comment by mbloch** [comment]
Closing as fixed
