### ISSUE TITLE
Merge layers, different attributes

### ISSUE THREAD

**Issue by nitrag** [mbloch/mapshaper#172]
I'm trying to merge two geojson sources with different attribute fields.

```
mapshaper -i FSCamp.geojson OSMcampsite.geojson combine-files \
        -merge-layers \
        -o format=geojson combined_campsite.geojson
```
```
[merge-layers] Fields missing from one or more layers ..........
```

I'm totally aware of that the fields are different and don't match and I'd like to ignore and continue anyway, however, I was thinking maybe this this a limitation of shapefiles? If so, would it be possible to merge when outputting to geojson then, exporting multiple layers into the one geojson feature collection?

Without the `merge-layers` two files are output'd.

**Comment by mbloch** [comment]
I like your suggestion to add the ability to combine multiple layers into a single GeoJSON output file. The simplest solution might be to automatically merge layers when you give the `-o` command a single output filename and specify multiple target layers, for example: `-o target=cities,roads output.json`.

An alternative would be to add a flag to the `-o` command, with a name like `combine` or `merge` or `singlefile`.

I like the first option, but am open to suggestions :)

**Comment by nitrag** [comment]
I like the second option (`combine-layers` or `merge-layers`) for several reasons:
- It's simple and what the user would be expecting
- how would I know what the name of the layers are when using `target=`?
- I personally can't think of a scenario where I would want to save only some layers into one file and the rest in another file. I would just delete the layer I didn't need.

The code to merge the features is simple, I just don't know where it belongs or how to loop through the layers!
```
geojson1.features = geojson1.features.concat(geojson2.features);
```

**Comment by mbloch** [comment]
The `target=` option is currently the standard way to output multiple layers. The `-o` command is consistent with most of mapshaper's other commands in this respect: unless the `target=` option is present, the implicit target of the command is set to the output of the previous command, which is usually a single layer.

Users can use the `-info` command to see the name and index of each layer, if they're not sure about how layers are named.

If we settle on `-o combine-layers` as the best option for combining output layers into a single GeoJSON file, it might be sensible to change the default target to be all layers (since most of the time this is what a user will want to do). If present, `target=` would override this default.

Implementing this feature is a bit more complicated than concatenating `features` arrays. I'm happy to do the coding myself. I'll probably have a new version published within a week. If you don't want to wait, you can use a different tool to merge GeoJSON files (e.g. https://github.com/mapbox/geojson-merge)

**Comment by nitrag** [comment]
Sounds good, no rush. I'm doing it in a separate script for prototyping but
I will eventually need to use mapshaper to filter on the features during
merge. Thanks!

**Comment by mbloch** [comment]
I included the `-o combine-layers` option in version 0.4.10, which should be published now.

**Comment by nitrag** [comment]
Works fantastically!
