### ISSUE TITLE
Dissolve for MultiPolygons - WebInterface

### ISSUE THREAD

**Issue by milnerm** [mbloch/mapshaper#179]
I have a small GeoJSON file (https://www.dropbox.com/s/llu2xyzk8w6zgfd/bath.json?dl=0) with several polygons - except one is a multipolygon. The web interface dissolves them all, except one polygon of the multi without issues. dissolve2 results in something slightly different.

Are multipolygons supported by mapshaper? or is this a bug? I can't seem to get the remainder of the multipolygon to dissolve, regardless of whether I use -dissolve or -dissolve2, or play with layers / clusters etc.

**Comment by mbloch** [comment]
Hi, I took a look at your source file in a text editor. The two-part polygon that did not dissolve correctly is the fourth feature in the file.

The problem here is that the geometry type of this feature is "Polygon", not "MultiPolygon". According to the GeoJSON spec, second and greater rings in a Polygon geometry should be holes in the first ring, not additional space-filling areas of the feature.

Do you know what software created your sample file? It seems to have generated invalid GeoJSON output.

**Comment by milnerm** [comment]
Hunh - will take a look. The GeoJSON is output from Leaflet. Perhaps it's getting ingested as polygons, not multi. will check. I'm aware of the Spec; just thought Leaflet output would be to spec...

**Comment by mbloch** [comment]
If this kind of invalid geometry turns out to be a common problem with GeoJSON files, then I'll add some code to handle it. This is the first time I've seen it, so I'm going to let it slide for now... thanks for reporting it :)
