### ISSUE TITLE
Uncomment "svg-scale" output option and add to wiki

### ISSUE THREAD

**Issue by ThomasThoren** [mbloch/mapshaper#184]
Is there a reason why the [`svg-scale` output option is commented out](https://github.com/mbloch/mapshaper/blob/master/src/cli/mapshaper-options.js#L211-L213)? It also isn't mentioned in the wiki's [output section](https://github.com/mbloch/mapshaper/wiki/Command-Reference#-o-output).

If there is more work to be done on the option, I would be happy to take a stab at it. Otherwise, I could uncomment the option and adjust the documentation so others are aware of this option. 

This is the exact function that I was searching for earlier today and it worked like a charm for me. I'd be glad to submit a pull request so others can get use out of it as well.

**Comment by mbloch** [comment]
Hi @ThomasThoren,

My memory is a bit hazy, but I think I left the `svg-scale=` option undocumented because I wanted to resolve some other issues relating to SVG export first, maybe you can help me think them through.

(I commented out the option's description in the file you referenced, so it doesn't appear in command line help, but the option can be used).

One issue is that the "viewBox" property of the svg element defaults to the bounding box of the coordinates in your dataset, which means that strokes and circle symbols can overflow the viewBox. The `margin=` option gives a way to expand viewBox beyond the coordinate bbox, but `margin` currently doesn't apply when `svg-scale=` is used.

It should be simple to update `margin` to work with `svg-scale`... once I do that, I'm ok with exposing the `svg-scale` option.

Eventually, I'd like to calculate viewBox bounds to include all of the ink on the page, but that can wait.

Another related issue is the scaling of point symbols (currently limited to circles). Currently you can use `-svg-style r=` to set the radius of circles in units of pixels or points. It seems to me that there should be a way to set symbol size relative to the map scale to complement the `svg-scale=` option. But I'm ok with documenting `svg-scale=` before this issue is resolved.

**Comment by mbloch** [comment]
Hi, I just released v0.4.45, which uncomments the `svg-scale=` option from the command line help. Also, `svg-scale=` can now be used in conjunction with the `margin=` option.

**Comment by ThomasThoren** [comment]
That's great! Thanks for these additions.
