### ISSUE TITLE
get bbox coordinates in mapshaper-gui through shift+drag

### ISSUE THREAD

**Issue by gka** [mbloch/mapshaper#186]
in mapshaper-gui shift+drag is setting the viewport. the same ui gesture could be used to retrieve the bounding box coordinates for use in `-clip bbox`.

there are several possible options to do this:
* the coordinates could be displayed instead of the x,y coordinates in the bottom left corner for a few seconds and then just disappear
*  after the shift+drag the bounding box could just get copied into the clipboard
* after the shift+drag there could be a tiny link in the bottom left corner saying "copy bbox coordinates" which would then copy it into the clipboard
* the bbox coordinates could also just be logged to the console, but I guess that's more for advanced users? would totally work for me though

**Comment by mbloch** [comment]
Hi Gregor, you've put your finger on a problem that I've wanted to solve for a while (how to get bounding box coordinates from the GUI).

I'm reluctant to use the same gesture for both bbox zoom and bbox info, because zooming is an annoying side effect if you just want the coords. I have a couple of alternatives.

The first alternative was simple to implement so I already added it to mapshaper.org. Now the mouse coordinates are always visible (before they appeared only in inspection mode). If you click on a point on the screen and keep mousing, you see bbox coordinates. To capture the coordinates, click again and select using Cmd-C. 

I'm thinking of a second alternative -- a multipurpose box tool. Using this tool, you would start by drawing a box. Once you've drawn the box, you have a number of things that you can do with it. You can use the mouse to fine-tune the box. You can view the box coordinates. You can use the box to clip the current layer. You can use the box to filter the intersecting features. You can create a new layer containing the box shape. Etcetera.

Looking forward to your feedback...

**Comment by mbloch** [comment]
I'd like to combine this with issue #91 (Interactive box tool)
