### ISSUE TITLE
Accept multiple files with -i

### ISSUE THREAD

**Issue by fitnr** [mbloch/mapshaper#189]
The `mapshaper -i` flag doesn't behave in line with it's help text:
```
-i input one or more files
```

The following command will convert three GeoJSON files into topojson in the directory `output`. (Acting on multiple files like this is a great strength of `mapshaper`):
```
> mapshaper a.json b.json c.json -o format=topojson output
[o] Wrote output/a.json
[o] Wrote output/b.json
[o] Wrote output/c.json
```

However, the equivalent command with the -i flag fails:
```
> mapshaper -i a.json b.json c.json -o format=topojson output
Error: Missing a -i command
Run mapshaper -h to view help
```

I know this is a kind of niggling error, but here's my use case: I'd like to use `mapshaper` with the many filenames variant of `find -exec`:
```
find input -exec mapshaper -o format=topojson output -i {} +
```

Note that for this to work, the command must end in `{} +`, so I'm currently limited to using the single file name variant of `find -exec`, which is much slower.

This is using `mapshaper 0.4.26`

**Comment by mbloch** [comment]
Hi,

It looks like you want to put the `-i` command after the `-o` command, as in your example from above:
`find input -exec mapshaper -o format=topojson output -i {} +`

This won't work -- mapshaper requires that commands be written in the order in which they are executed.

Is the following exactly the command that you ran?
`mapshaper -i a.json b.json c.json -o format=topojson output`

I can't reproduce the error that you pasted above with that command. If you put the `-i` command after the `-o` command, however, I do see that message.

**Comment by fitnr** [comment]
Argument order matters! A little unusual, but I get that it makes sense for mapshaper.

I made a mistake about the result of `mapshaper -i a.json b.json c.json ...`, so about forget that. Sorry for the error.

**Comment by mbloch** [comment]
I switched to the current syntax because I wanted to be able to support something like a pipeline of commands. I think imagemagick has a similar syntax. It seemed strange to me at first too, since it's different than typical Unix-style command syntax.

If I want to import multiple files without typing out the file names, I have to rely on shell expansion (wildcards) to target the files... please let me know if you have a better idea.

**Comment by fitnr** [comment]
I rely on shell expansion as well, although I've recently been intermittently getting the dreaded "too many arguments" error from bash. Since the `find -exec {} +` format won't work, I'll use something like `echo input/*.json | xargs -J % mapshaper -i % -o format=topojson output`.

**Comment by mbloch** [comment]
Here's a trick to can try to work around "too many arguments" ... try enclosing your filename expression in quotes, like this: `mapshaper "*.geojson"`

This bypasses shell expansion. Mapshaper will then try to do its own expansion. I had to build filename expansion into mapshaper in order to support the windows CMD shell, which doesn't do expansion.

**Comment by fitnr** [comment]
Ooh, great trick. I've written very [similar code](https://www.npmjs.com/package/glob-concat), for handling a mix of file names and globs, although I never tested it on Windows.
