### ISSUE TITLE
”unsupported WKT definition“

### ISSUE THREAD

**Issue by yancongwen** [mbloch/mapshaper#193]
Hi,
How can I use the proj that haven't definition in the project? thanks!

**Comment by yancongwen** [comment]
my proj is a Local coordinate system,I want to out both the shp file and proj file

**Comment by mbloch** [comment]
Hi,
I added .prj file support recently, and there are likely to be some bugs. Did you get this error message when importing a Shapefile? If so, could you send me the .prj file from your Shapefile so I can see why it failed?

You can define the coordinate system of a data layer using a Proj.4 definition string, if the .prj file fails to load. But if Mapshaper was unable to read the original .prj file, it is unlikely to be able to export a .prj file for your dataset.

**Comment by yancongwen** [comment]
Hi,
Thanks for your replay!
"Error: [o] Unusable .prj file (unsupported WKT definition: Beijing_1954_3_Degree_GK_CM_114E)"

[wuhan_shp.zip](https://github.com/mbloch/mapshaper/files/1132678/wuhan_shp.zip)

**Comment by mbloch** [comment]
Thanks, I'll try to add support for this coordinate system over the weekend.

**Comment by yancongwen** [comment]
Thanks for you enthusiasm! 
 Because there are many coordinate systems in the words, this project will never support all of them. Now ,this project has defined some world wide coordinate systems,but it not enough. Does this project support defining coordinate systems myself ?

**Comment by mbloch** [comment]
Hi, I just published a new version, v0.4.29, that should fix the error that you encountered.

Previously, Mapshaper was unable to parse your .prj file because it did not recognize "Gauss_Kruger" as a valid projection name. I fixed this.

To answer your question, yes, you can define custom coordinate systems, if you can define the projection using the Proj.4 format.

It appears that your .prj file is the ESRI version of EPSG 2435 (https://epsg.io/2435).

The ESRI .prj file is missing the "TOWSG84" parameter that is present in the OGC .prj file and the Proj.4 definition that are linked to on the above page. If you want to reproject your file, you will get slightly different results using your current .prj file vs. using the OGC .prj file or the Proj.4 definition.

**Comment by yancongwen** [comment]
Thanks! 
I am profoundly grateful for your help!

**Comment by mbloch** [comment]
Thanks for filing the issue, it helps me improve mapshaper :)
