### ISSUE TITLE
KML support

### ISSUE THREAD

**Issue by HarryStevens** [mbloch/mapshaper#229]
People often share geospatial data in KML format because they were using it with Google Maps or Fusion Tables. It would be useful for mapshaper to support KML, both for uploads and for conversions.

**Comment by mbloch** [comment]
I'll consider adding KML support... meanwhile, have you tried `ogr2ogr` or `togeojson`?  They were suggested on this thread: https://gis.stackexchange.com/questions/92885/ogr2ogr-converting-kml-to-geojson

**Comment by amenadiel** [comment]
I'd reccoment Mapbox's togeojson. It feels more smooth in general. Besides, ogr2ogr still depends on gdal-bin being installed at a server level.

(I still use ogr2ogr as well, bc it deals with, ahem, zipped shapefiles)

**Comment by HarryStevens** [comment]
The newspaper I work for hosts lots of geospatial data on our GitHub account (https://github.com/HindustanTimesLabs/shapefiles/). I like to include KML files because many people use Google Fusion Tables for mapping. I use MapBox's tokml (https://github.com/mapbox/tokml) to convert files to KML, but I use mapshaper for lots of other stuff. So if mapshaper supported KML, then I could just use it for everything.

**Comment by amenadiel** [comment]
But you would be including extra weight in mapshaper that not everyone would use. So why don't you just create a project that glues thing together?  That's what I did after @mbloch said that CLI mapshaper wouldn't support zipped shp files anytime soon. I just glued things together and made a pipeline.

If we're talking about web GUI, you can use Mapbox's browser version of `@mapbox/togeojson` to intercept file drag-n-drop, create a new Blob, then send that geojson blob to the usual pipeline.

**Comment by mbloch** [comment]
Hi, everyone is making good points. I'm not opposed to adding support for more file formats in principle.  One of my goals for mapshaper is to develop an efficient, streamlined workflow. Being able to import and export directly to your desired file format is certainly a convenience.

But because mapshaper is a side project that I work on in my limited free time, I have to pick and choose what features to work on. I'm going to put support for new file formats aside for a while so I can work on finishing some exciting (to me) new features.

I'm closing this issue for now, and I've noted the request for KML support.

**Comment by ilovefreesw** [comment]
KML export is not yet added :(
