### ISSUE TITLE
-dissolve on large dataset creates artifacts

### ISSUE THREAD

**Issue by swbloom** [mbloch/mapshaper#249]
I have a million+ polygon features in 1x1km tiles over Alberta that I am trying to dissolve by attribute in order to simplify them into larger shapes. Each tile has a `Rank` attribute of 1 to 4.

When I run this dissolve command:
`mapshaper input.shp --dissolve Rank -o output.shp`

and upload the result into Mapbox to do some visualization, I can see that a lot of the tiles have been sliced in half or hollowed out. 

I tried running `--dissolve2` to see if that might work better, but I received an 
`[dissolve2] Error: Expected a polygon layer`

Here's what the map looks like currently:
https://api.mapbox.com/styles/v1/twg-wwf/cjav9mtwolsju2sqvnuz844zw.html?fresh=true&title=true&access_token=pk.eyJ1IjoidHdnLXd3ZiIsImEiOiJjamFzazQ2bnU0dGthMnpwbDl4NnM1amptIn0.ObLljExu4Li3NscRe1lanQ#7.62/57.864/-114.8

I can also provide the initial data set if this would help!

Thank you so so much in advance!

**Comment by mbloch** [comment]
Hey... if you send me a link to download your original input Shapefile, I'll check it out.

**Comment by swbloom** [comment]
Sure! Is there any chance I could shoot it to you in an email?

**Comment by mbloch** [comment]
That would be fine, thanks

**Comment by mbloch** [comment]
Simon,

I had a look at your Shapefile. Here are some instructions for converting the individual cells into larger polygon shapes.

The Shapefile's "type" is POLYLINEZ (i.e. lines not polygons). To work with it in mapshaper, the first step is to convert it to a polygon type. (Mapshaper can't do this yet -- I'll file an issue to add this functionality). You can do the conversion in QGIS using the "Vector -> Geometry Tools -> Lines to polygons" command.

The next step is to import the polygon Shapefile into mapshaper using the `snap-interval` command line option, because the vertices of adjacent cells are not perfectly aligned in your file. I used `snap-interval=10`.

After this, you should be able to dissolve the cells cleanly. "-dissolve2" worked well for me.

Here are the commands to use in the CLI. This method also worked for me in the browser (I used Firefox).

```
mapshaper polygons.shp snap-interval=10 -dissolve2 NatRegion -o out.shp
```

(The above command took 45 seconds on my laptop.)

Thanks for sending your file, this helped me think of a few ways to improve mapshaper.

**Comment by swbloom** [comment]
Sorry for delaying the response on this - just wanted to thank you for the help - ran the following command and the dissolve worked successfully!
