### ISSUE TITLE
Standalone optimized canvas viewer

### ISSUE THREAD

**Issue by kmturley** [mbloch/mapshaper#258]
Thanks for making mapshaper, it's a very useful tool and it is referenced in many blogs and tutorials. The tools are great but a little too many files for what I need, so I'm creating a simplified set of d3 map tools at:
https://github.com/kmturley/d3-map-toolkit

My canvas viewer starts to slow down as I add more points e.g. states:
https://kmturley.github.io/d3-map-toolkit/src/#states

But your viewer runs silky smooth using the same json file:
https://kmturley.github.io/d3-map-toolkit/src/json/states/6.toposimplify.json

I was looking at your optimized canvas viewer rendering code, specifically around drawPaths():
https://github.com/mbloch/mapshaper/blob/b8ab6418f46684b946a778d90f029d3f5392c77f/src/gui/mapshaper-canvas.js#L76

You are drawing the paths yourself? and then caching the shapes in getShapePencil():
https://github.com/mbloch/mapshaper/blob/b8ab6418f46684b946a778d90f029d3f5392c77f/src/gui/mapshaper-canvas.js#L297

I tried to unpick the rendering logic, but it's tied heavily into your viewing area code, and nested data sets.

The feature list i'm trying to build is:
- optimized canvas viewer for more complex maps
- add layer using json file (topojson, geojson)
- support different projections (d3)
- drag, pan and zoom controls
- mobile support
- tap to highlight features

Nice-to-haves would be:
- inertia support for panning
- layers of detail show/hide based on zoom level
- ability to add/find points using lat/long coordinates

I was wondering if you'd be interested in creating a separate standalone canvas viewer, which mappers can embed on their sites?

In the meantime I'm going to continue and see the other limitations I hit as I go!

**Comment by mbloch** [comment]
I don't have time to work on a standalone viewer, but I can give you a few suggestions.

The main reason mapshaper renders fairly quickly is because it draws strokes but not fills. If you add both strokes and fills in mapshaper using the `-svg-style` command, then render time is in the same ballpark as your viewer.

There are a few optimizations that help a bit. For example:
* When zoomed-out on a complex dataset, mapshaper displays a simplified version of the shapes.
* When drawing many shapes with the same style, you can get a speedup of up to 2x or 3x if you draw a bunch of shapes before calling the Canvas API functions `fill()` and `stroke()`.

But 2D Canvas may never perform very well for rendering complicated map shapes.

**Comment by kmturley** [comment]
Thanks for the suggestions, will investigate it more and update my viewer!

**Comment by stripathix** [comment]
Hi @mbloch By optimization point `When zoomed-out on a complex dataset, mapshaper displays a simplified version of the shapes.` do you mean use topojson.simplify() to simplify it when zoomed out?

**Comment by mbloch** [comment]
Something like that. Mapshaper makes a simplified copy of large data layers in-memory, using a function similar to topojson.simplify().
