### ISSUE TITLE
where= command in Web vs Node 

### ISSUE THREAD

**Issue by TheMapSmith** [mbloch/mapshaper#264]
Hello,

I'm trying to figure out the `where=` clause associated with an `-svg-style` command. I'm able to execute this command in the web interface successfully

`$ -svg-style where='QPF>1' fill=red`

But when I try to run it in Node I get this error:

'{ UserError: ReferenceError in expression [QPF>1]: QPF is not defined'

Here is my code.
https://github.com/TheMapSmith/qpf/blob/429f43658904dd3ff117b464dd5b14a639c74052/index.js#L7

Any tips would be helpful.

Thanks for making such a great tool!
~Stephen

**Comment by mbloch** [comment]
Hi Stephen,

The `applyCommands()` function is designed to accept file content in the second parameter. You're giving it the path to your `.shp` file. Apologies for not documenting these functions better!

Mapshaper should have thrown an error in this situation... I just published a new version that fixes this.

To read input from a file, you can put the file path in your command string, the same as if you were running the command line mapshaper program. So your script would look like this (with processing commands omitted):

```
var command = '-i _data/QPF168hr_Day1-7_latest/97e2200.shp -o format=svg';
mapshaper.applyCommands(command, {}, function(err, out) {
	// write output file
});
```

Because you're just writing the output to a file, it would be simpler to use the `runCommands()` function, which writes output to a file instead of passing it to a callback function, like this:

```
var command = '-i _data/QPF168hr_Day1-7_latest/97e2200.shp -o _out/97e2200.svg';
mapshaper.runCommands(command, function(err) {
	// check for error
});
```

P.S. If you do decide to use `applyCommands()` for Shapefile input, you should include entries for the `.dbf` and `.prj` files in addition to the `.shp` file.

**Comment by TheMapSmith** [comment]
Hey Matthew, thanks so much for the tip, that was very helpful. I was operating under the assumption that `applyCommands()` was for putting multiple commands together. 

Here is my updated code: https://github.com/TheMapSmith/qpf/blob/acdc56dcd55bdcea1c6be84b72aea1f5b4ee7c97/index.js

**Comment by mbloch** [comment]
For creating sequential color schemes, you could also try the `-colorizer` command, which defines a function for converting data values to colors, like this:

```
-colorizer name=fillColor breaks='.1,.25,.75,1.5,2.5,3.5,4' \
  colors='white,#5EF8F9,#55D3DC,#4EAFBE,#468C9E,#3C6C7E,#304D5D,#21313D' \
-svg-style fill='fillColor(QPF)'
```
