### ISSUE TITLE
Error: [PathImporter] Mixed feature types are not allowed

### ISSUE THREAD

**Issue by PriancaSingh** [mbloch/mapshaper#292]
Hi,

Earlier I used Mapshaper to simplify my geojson file , it simplifies and writes are coordinates in a single file, but now in mapshaper version 4 onwards, when I tried to did the same,I got my file spilitted into 2 files, some of the feature properties moved to the another file that is simply not in my requirement.

Can some body please help how can I simplify my file and writes the same in a single file only. I have attached sample file as well. This file is .json format

[sample.txt](https://github.com/mbloch/mapshaper/files/2215209/sample.txt)

**Comment by mbloch** [comment]
Hi,

As I remember, earlier versions of Mapshaper threw an error when you tried to import a GeoJSON file containing different geometry types.

The current version imports points, lines and polygons to different layers. This is because Mapshaper layers are limited to one kind of geometry.

You can export different-typed layers to the same GeoJSON file if you use the `combine-layers` option. So on the command line, you would do something like this: `-o combine-layers target=* output.json`. In the web interface, you would add `combine-layers` to the text box labeled "command line options". This worked for me when I tested your sample file.

Hope this helps!

**Comment by PriancaSingh** [comment]
Thank you.. It works..
