### ISSUE TITLE
Catch common -join mistakes

### ISSUE THREAD

**Issue by mbloch** [mbloch/mapshaper#306]
One common mistake is to try to join a numeric field to a string field. This can happen when one dataset contains numeric versions of data like ZIP codes or FIPS codes, which look like numbers but should be strings. Joining numbers to strings could trigger an error. Also, in the Web UI inspector, the difference between numbers and strings should be clearer (currently numbers are shown in italics). I'd appreciate any suggestions.

**Comment by mbloch** [comment]
Commit 8b6381660bc57f135ea0 addresses this

**Comment by 2803media** [comment]
How do you manage this error:

`[join] Error: Join keys have mismatched data types: string and number`

My script works well but with some csv I had this join error and can't find a way to debug it.

Thanks for your light  @mbloch

**Comment by 2803media** [comment]
I understand!  One of my id is 024660000E0156 and js interpret this like 2.466e+156, so like a number.... I just need to find a way to pass this string as a string not a number...

keys=id,id2

**Comment by mbloch** [comment]
mapshaper will auto-convert CSV fields to numbers if all the values can be parsed as numbers. You can prevent type conversion by adding a `string-fields=<fields>` argument to either the `-i` or `-join` commands. Does this help?

**Comment by 2803media** [comment]
Brillant ! This works very well.
Thanks again Matthew for this great software

**Comment by bonnjorr** [comment]
@mbloch This is really, really not working for me. I'm using the online version. No matter where I put the string argument, it does NOT change any of the data types. Why would it not just automatically do this anyway?

**Comment by bonnjorr** [comment]
@mbloch I have a US map with counties, the shape file (A). Each county has a numeric id field that mapshaper sees as a string field (not italicized). There is no field with the stare name. I need to join this to a csv file (created in excel) with the same field, but mapshaper is switching it to a numeric field (italicized). I've tried to use the "string-fields=" argument in as many permutations of the join function as possible and it keeps throwing the same error. 

It would be fine if I could filter the shape file by the first two characters like a "left" function like sql or excel but I don't know enough js. Seems very involved. 

Or maybe the issue is that shape file has 2000 polygons (full country) and the csv has only 100 records (one state). 

Any help you can give on how to do this would be great. Or if you could direct me to a resource that could teach me the language...starting with js fundamentals that'd be great. Mapshaper is incredible. It's just doesn't like casual users. 😂

**Comment by mbloch** [comment]
Apologies for the lack of introductory documentation... I built mapshaper mostly to help me and my colleagues with our work, I haven't had much time to promote it for a broader audience.

It sounds like the numeric ids you're referring to are probably five-digit county FIPS codes, which should be imported as strings. (I'm assuming has a corresponding String-type field containing county FIPS codes).

As the first step in troubleshooting the join, let's make sure we are importing the FIPS codes from the CSV as strings. Assuming you're using the web UI, you would add the `string-fields=` option to the import options dialog, as shown below (I'm calling the FIPS field `COUNTYFP`, you would use a field name from your CSV).  The `string-fields` option is how to tell mapshaper that data that looks numeric should be imported as strings.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/1232222/236842448-5f18b301-98b7-4d1c-93a3-6c4fa2fdcc5f.png">

If this works, joining the CSV to the Shapefile should be easy.

**Comment by bonnjorr** [comment]
That did it! So simple. Thank you so much.
