### ISSUE TITLE
I am confused by -lines fields output - I expected information to be passed to outputed geometry

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#318]
`mapshaper -i test.geojson -lines fields=building -o out.geojson` with file `test.geojson`:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "id": "way/52004195",
      "properties": {
        "building": "test_value"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              19.9275616,
              50.0560056
            ],
            [
              19.92,
              50.055978
            ],
            [
              19.9274007,
              50.055978
            ],
            [
              19.9275616,
              50.0560056
            ]
          ]
        ]
      }
    }
  ]
}
```

gives output

```
{"type":"FeatureCollection", "features": [
{"type":"Feature","geometry":{"type":"LineString","coordinates":[[19.9275616,50.0560056],[19.9274007,50.055978],[19.92,50.055978],[19.9275616,50.0560056]]},"properties":{"RANK":0,"TYPE":"outer"}}
]}
```

Based on https://github.com/mbloch/mapshaper/wiki/Command-Reference#-lines I expected the building value to be passed into outputed geometry as one of properties.

**Comment by mbloch** [comment]
The purpose of the `fields` option is not to pass data from polygon to line features. The `fields` option is useful for identifying different types of interior boundaries in a polygon mosaic (e.g. to distinguish between provincial borders and county borders in a county layer).

There is not a simple way to pass polygon attributes to line features using the `-lines` command. That's because `-lines` converts the boundary between two adjacent polygons to a single line feature, and the adjacent polygons are likely to have different data values associated with them.

**Comment by matkoniecz** [comment]
In my specific case it is possible to do it in a reasonable way as I `dissolve2` as the first step. 

But as it is impossible/hard to generalize I will do some custom processing of my data. I guess that I should look for some geojson processing tool to avoid writing (and debugging) my own tool.
