### ISSUE TITLE
simplify can create invalid geometries

### ISSUE THREAD

**Issue by ateucher** [mbloch/mapshaper#352]
This is more of a heads-up than a bug or feature request, but `simplify` can create invalid polygons:

```
~ $ echo '
{
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "id": 1, "properties": { "Example": "Minimal" }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 3.0, 1.0 ], [ 1.0, 2.0 ], [ 2.0, 3.0 ], [ 1.0, 4.0 ], [ 3.0, 5.0 ], [ 5.0, 4.0 ], [ 4.0, 3.0 ], [ 5.0, 2.0 ], [ 3.0, 1.0 ] ] ], [ [ [ 7.0, 1.0 ], [ 5.0, 2.0 ], [ 6.0, 3.0 ], [ 5.0, 4.0 ], [ 7.0, 5.0 ], [ 9.0, 4.0 ], [ 8.0, 3.0 ], [ 9.0, 2.0 ], [ 7.0, 1.0 ] ] ] ] } }
]
}' > foo.geojson
~ $ ogrinfo foo.geojson -q -dialect sqlite -sql "select st_isvalid(geometry) from foo"

Layer name: SELECT
OGRFeature(SELECT):0
  st_isvalid(geometry) (Integer) = 1

~ $ mapshaper foo.geojson -simplify 0.6 -o bar.geojson
[o] Wrote bar.geojson
~ $ ogrinfo bar.geojson -q -dialect sqlite -sql "select st_isvalid(geometry) from bar"
GEOS warning: Self-intersection at or near point 5 2

Layer name: SELECT
OGRFeature(SELECT):0
  st_isvalid(geometry) (Integer) = 0
```
(visual of `foo.geojson` and `bar.geojson`: https://gist.github.com/ateucher/228c7bba931d3a5387a14c735a87cd0c)

The output (`bar.geojson`) is invalid in that it violates the [simple features specification](https://www.opengeospatial.org/standards/sfa) 6.1.11.1 part c) "No two Rings in the boundary cross and the Rings in the boundary of a Polygon may intersect at a Point but only as a tangent (i.e. at a point common to the two curves, nearby points cannot be common)".

I'm not sure what (if anything) you might want to do to address this, but I thought I would let you know, as this came up in my [rmapshaper](https://github.com/ateucher/rmapshaper) R package (https://github.com/ateucher/rmapshaper/issues/89).

**Comment by mbloch** [comment]
I reproduced your test case (thank you for providing detailed info !)

As you noted, the output violates the Simple Features specification (it produces a multi-polygon containing two rings that touch each other along a line segment). I gather that this could cause problems with software that uses the Simple Features standard, like PostGIS.

I'm reluctant to add Simple Features compliance to the -simplify command, because it could slow down the command a lot, and most users probably don't need compliant output.

Running -clean after -simplify can fix a lot of issues (including this one). It makes sense to me to add Simple Features compliance as an explicit requirement for the -clean command.

So my current preference is to leave -simplify the way it is and require that -clean produces Simple Features-compliant output. Does that make sense to you?

**Comment by nvkelso** [comment]
+1 for adding option to be **Simple Features**-compliant. I've spent far too many hours of my life arguing with PostGIS about this kind of thing!

I don't have a strong opinion about which command to add it to. Adding it to `-clean` seems fine to me.

**Comment by ateucher** [comment]
I think adding it to `-clean` makes perfect sense, I like separation of tasks :)

**Comment by mbloch** [comment]
Ok, then! I'll plan to add more tests for the -clean command, specifically to target Simple Features compliance.

**Comment by mbloch** [comment]
Recently I've improved the `-clean` and added some tests for Simple Features compliance. I think this issue can be closed, but please file a new issue if you have an example of non-compliant output from the `-clean` command.
