### ISSUE TITLE
Make "internal" as independent js file

### ISSUE THREAD

**Issue by kochizufan** [mbloch/mapshaper#359]
Hi,

I use this module in my project
https://github.com/code4history/MaplatTin

But, your module includes
```
require('fs')
```
so webpack causes error like this:
```
Module not found: Error: Can't resolve 'fs'
```
This means, 'fs' module does not exist in the browser, so webpack can't compile this to browser-side use.
So, currently, I use your module not from npm but copied it into my repository.
https://github.com/code4history/MaplatTin/blob/master/src/mapshaper-maplat.js

What I used in my project is only "internal" API, so if you make internal APIs into independent js file, I can call it from npm.
Is this possible?

**Comment by mbloch** [comment]
I'm not a Webpack expert... but can you declare the modules that trigger Webpack errors as "externals"?

Docs: https://webpack.js.org/configuration/externals/

Also, this issue might be relevant: https://github.com/webpack-contrib/css-loader/issues/447
You can try adding this to the webpack config file:
```
node: {
  fs: 'empty'
}
```

**Comment by mbloch** [comment]
One thing to be aware of... the "internal" functions are not really an API that you can depend on... they might change from one release to another.

I've been developing mapshaper mostly as an end user application, not so much as a library for other developers to use (although of course you're welcome to use mapshaper however you like) I'm going to close this issue, because I want to give priority to the needs of end users, not developers. 

Best,
mbloch :)
