### ISSUE TITLE
Unexpected error on label-text with text containing ( character

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#363]
`mapshaper -i empty.geojson -style label-text="(" -o label.svg`

with empty.geojson

```
{
  "type": "FeatureCollection",
  "features": []    
} 
```

results in `[style] SyntaxError in expression [(]`

To avoid XY problem: I was trying to render `mapshaper -i point.geojson -style label-text="dane © OpenStreetMap (licencja ODBL)" -o label.svg`

As workaround I went with `mapshaper -i point.geojson -style label-text="dane © OpenStreetMap - licencja ODBL" -o label.svg`

**Comment by mbloch** [comment]
Currently there's a too-simple heuristic for testing if `label-text` is a JS expression or a literal string:  text that includes some common JS syntax characters or is the name of a data field is treated as an expression. Other content is treated as a literal string. That's why you get a 'SyntaxError' message for strings containing parentheses.

One solution would be to treat all strings that trigger syntax errors as literal strings.

The downside of this approach is that actual JS expressions that contain syntax errors won't trigger an appropriate error message.

A better solution might be to find a more sophisticated test for whether a string contains a JS expression.

Any suggestions?

**Comment by matkoniecz** [comment]
Maybe just give a better error message?

Something like

`label text includes common JS syntax characters or is the name of a data field and was treated as JS expression that failed with $ERROR` 

And maybe include hint what should be done if someone really wants to display brackets in label - in my case I was able to rephrase it, but it may be not always possible.

**Comment by mbloch** [comment]
I've changed the way mapshaper handles the `-style label-text=` option.  Now strings that are not valid JS are treated as ordinary text, including the string that caused the error for you.
