### ISSUE TITLE
-v and --version are writing to stderr

### ISSUE THREAD

**Issue by christian-weiss** [mbloch/mapshaper#364]
Latest NPM on alpine.
`mapshaper -v` and mapshaper `--version` are printing `v0.4.137` to stderr.
Should output version string to stdout.

**Comment by mbloch** [comment]
Currently Mapshaper's informational messages all print to stderr. My thinking was that if users want to output their data to stdout, they can be sure no messages get mixed in.

It's possible `-v` is a special case, and should be printed to stdout. Why is that?

**Comment by christian-weiss** [comment]
One example for WHY:
https://github.com/Freifunk-Hamm/docker_mapshaper/blob/master/local_build.sh#L15

**Comment by christian-weiss** [comment]
To be semantically correct, please use stderr for errors and warnings only. Not for normal information.

The version string is normal information, that a user is allowed to expect on stdout when you asked for a version string (`-v`).

If your default behaviour is to write data to stdout, then you should send errors to stderr and normal log data to a log file be default or stay silent as long as a `--log filename` was not defined. Or mix data and log in stdout if `--log filename` was is not defined.

An option `--output filename` is also good if it is available.

**Comment by mbloch** [comment]
I agree that printing the version number to stdout is the expected behavior, and being able to save the version to a shell variable without having to use redirection seems desirable, so I'm willing to make this change.

I think that many programs use stderr for program status messages in addition to errors and warnings. I don't see this as 'semantically incorrect'. I want to keep using stderr for status messages.

There is a `-quiet` option if you want to inhibit status messages and only use stderr for errors.

**Comment by mbloch** [comment]
I just published v0.4.139, which prints the version number to stdout.
