### ISSUE TITLE
-info is not going to stdout

### ISSUE THREAD

**Issue by hoffrichterm** [mbloch/mapshaper#402]
When i use mapshaper shapefile.shp -info the output can not be used by grep or piped through an own script.

**Comment by mbloch** [comment]
Output from `-info` gets sent to stderr because I've been using stderr for status and debugging messages and stdout for data. The distinction between the two kinds kinds of output is not alway clear, though, as your situation shows.

Perhaps mapshaper needs a separate command for printing information about datasets that has a more consistent, data-y format than the -info command output.

But meanwhile, you can always redirect stderr to stdout. In bash, I think you go: ` 2>&1 |`
