### ISSUE TITLE
proj webmercator issues(on polylines?)

### ISSUE THREAD

**Issue by nonoumasy** [mbloch/mapshaper#419]
I exported 3 geojson from overpass. Each contains polylines which I loaded into mapshaper. Everytime I try to use 'proj webmercator'. the lines disappear. They're still in the layers but just hidden. When I delete one of the geojson, the other two come back but their projections have not been applied. Not sure if this issue has cropped up yet.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6312676/83608373-b06aef00-a531-11ea-9eb5-56af3cc9c8d3.gif)

**Comment by nonoumasy** [comment]
I found a solution and maybe the cause. My solution was to import each geojson one at a time and then project it to webmercator using 'proj webmercator'. Then I did this for the other 2 geojson files. I guess you can't apply the proj when you load more than one geojson.

**Comment by mbloch** [comment]
In the web UI, the commands you run in the console are applied to the currently selected layer only, by default. If you want to project all of the layers, you have to target them all, like this: `-proj webmercator target=*`.   When you ran `-proj` on a single layer, the other layers seemed to disappear because their coordinates no longer matched the coordinates of the selected layer.
