### ISSUE TITLE
Web: Export fails when specifying radius export option

### ISSUE THREAD

**Issue by blackboxlogic** [mbloch/mapshaper#436]
Using the web interface, I've imported a file with points. When I export them as svg they don't have a radius set. Looking through the [documentation](https://github.com/mbloch/mapshaper/wiki/Command-Reference#-style), I see that radius is configurable.
I select _Export_, choose _SVG_, and put `-style r=5` in the _Export Options_ field.

When I click _Export_, I get: `Export failed for an unknown reason`

- Is this user error and my option string is malformed?
- Is the tool broken?

**Comment by mbloch** [comment]
Here's what you need to do: after loading your file, open the command console by clicking on the "Console" button, then enter `-style r=5` at the command line prompt. Then you can export the points as SVG.

I'll try to add a more informative error message... 

Cheers,
mbloch

**Comment by blackboxlogic** [comment]
Thank you, that worked and my issue is resolved. As a new user, the `export options` field seemed like the place to put that command text. Especially since the tool tip says "Enter options from the command line interface". If you think others might make the same mistake, that tool tip could clarify which options it can take.

**Comment by mbloch** [comment]
I updated the tooltip text to read "Enter options from the command line interface for the -o command" -- I hope that's somewhat less misleading.

I know that first-time users have a hard time using this tool. I'm slowly working on setting up a documentation website with resources for users of all levels. It's been slow going, because I don't have much time to work on mapshaper.
