### ISSUE TITLE
Exported TopoJSON file contains intersecting lines

### ISSUE THREAD

**Issue by stevemaughan** [mbloch/mapshaper#468]
I downloaded a GeoJSON file of postcodes for Germany from here:

[https://www.alignmix.com/geographic-data/](https://www.alignmix.com/geographic-data/)

I then imported the GeoJSON version into MapShaper.org. There were no line intersections identified. I didn't change the file, I just exported it as a TopoJSON files. I then refreshed the browser and imported this new TopoJSON file back into MapShaper.org. To my surprise, it contained 10 line intersections. Surely this is a bug?

— Steve

**Comment by mbloch** [comment]
This probably isn't a bug, exactly. Mapshaper applies a default amount of "quantization" (basically, rounding) to the coordinates in your data. Rounding coordinates commonly introduces intersections. The same thing happens if you reduce the precision of your exported GeoJSON coordinates. 

To disable quantization, you should add the `no-quantization` flag to the export options, as shown in the image below.

If you are still seeing new intersections when using the `no-quantization` option, then there probably is a bug.

![image](https://user-images.githubusercontent.com/1232222/109986456-c0d41400-7cd3-11eb-8445-bd049faf4b91.png)

**Comment by stevemaughan** [comment]
It now shows no errors. Many thanks!
