### ISSUE TITLE
Broken -proj EPSG:3857 after bdabf38d commit

### ISSUE THREAD

**Issue by cardid-zz** [mbloch/mapshaper#489]
How it works before bdabf38d commit
Convert successful
![изображение](https://user-images.githubusercontent.com/2221336/119464275-c38f5400-bd6c-11eb-9f36-8786ca280f17.png)
After  bdabf38d commit all polygons were deleted
![изображение](https://user-images.githubusercontent.com/2221336/119464448-efaad500-bd6c-11eb-89af-0b809526cb90.png)

File to test [file.geojson.txt](https://github.com/mbloch/mapshaper/files/6537734/file.geojson.txt)

**Comment by mbloch** [comment]
Hi, thanks for reporting this! I published an update that should fix this.

I think the problem was that mapshaper started calling the 'clean' function post-projection, which had the effect of merging overlapping polygons. (The default behavior of -clean removes overlapping polygons). I fixed this, and your file appears to project correctly now.

**Comment by cardid-zz** [comment]
Many thanks!
