### ISSUE TITLE
Number format with comma separator for decimals in csv

### ISSUE THREAD

**Issue by gurmanbh** [mbloch/mapshaper#495]
I have a csv with numbers as `46,4`. Where the decimal separator is a comma. While mapshaper recognises them as number fields, the colorizer does not work on them. However, if I change the commas to periods, it works just fine. Is there a way to deal with this without changing the csv?

**Comment by mbloch** [comment]
Hi, can you send me a sample data file with comma decimal separators? That will help me add this feature.

**Comment by gurmanbh** [comment]
Merged this on a shapefile for Kyrgyzstan 
[poverty_rate.csv](https://github.com/mbloch/mapshaper/files/6872974/poverty_rate.csv)

**Comment by gurmanbh** [comment]
Here is a geojson with the data if that helps.
[merged.txt](https://github.com/mbloch/mapshaper/files/6872981/merged.txt)

**Comment by mbloch** [comment]
Thanks for the sample files!

One approach would be to add an option to the `-i` and `-o` commands, perhaps `csv-decimal-char=,`. This would not be hard to implement.

I noticed that the `y2020` field in `poverty_rate.csv` contains a decimal comma in the first record and decimal points in the later records -- the decimal separator is inconsistent.  It would be tricky to try to import numbers with inconsistent separators automatically. (This is because numbers in csv fields sometimes also include thousands separators, so there could be ambiguous cases). How would you suggest handling data with inconsistent separators? Treating it as an error and stopping the program? Or something else?

I should mention that there is a kludgy way you could import comma-separated numbers currently. Here's an example of importing a single field:

```
mapshaper -i poverty_rate.csv string-fields=y2020 -each 'y2020 = +y2020.replace(",", ".")'
```

**Comment by gurmanbh** [comment]
That inconsistency in the separators might have been my doing. Maybe I left a value while manually changing it. Sorry about that. 

`csv-decimal-char=,` sounds like an excellent solution! That would be incredibly helpful.

**Comment by mbloch** [comment]
Hi, the latest version (v0.5.62) adds the `-i decimal-comma` option. This option imports numbers with comma-separated decimals from CSV files. It also handles numbers that use either points or spaces as thousands separators (since these conventions are also used in locales that use decimal commas).

I didn't add an equivalent option to the `-o` command. This is because an adequate solution for formatting output numbers would have to support a larger range of formatting options, such as choosing points or spaces for grouping digits, and using groups of four digits instead of three digits (China), etc.

I may add full locale support in the future... but for now, the `decimal-comma` option should be useful for importing numbers.

**Comment by mbloch** [comment]
I went ahead and added `-o decimal-comma` for outputting CSV numbers with decimal commas... I realized that this might still be useful even if mapshaper doesn't support formatting numbers with different kinds of group separators and other variations.

Thanks for filing this issue :)
