### ISSUE TITLE
Website output is broken/missing countries

### ISSUE THREAD

**Issue by PaulFranken** [mbloch/mapshaper#557]
Hello. 

I'm trying to convert this file (https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces.zip) to topojson through the online interface at mapshaper.org. It loads in fine and shows all the detail you would expect.

However, when i try to load the export into my programs it seems half the countries are flat-out missing. I've tried many combinations of parameters and simplifications, but no dice.

I couldn't find any other issues detailing this problem.

**Comment by ThomasG77** [comment]
I've tried to load the mentioned file and export to topojson. Then, I've tried to open it in another software e.g QGIS and it appears fine. IMHO, the issue is with the aforementioned "load the export into my programs". The issue does not seem to be in mapshaper export to topojson but in "your programs". You may better investigate on how you load the export but I could be wrong.

**Comment by PaulFranken** [comment]
Odd. I'm trying to test out AirBnB's VisX package(more specifically this demo here: https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-geo-mercator?file=/Example.tsx), which seemed to render the included topojson file just fine, but not my export. At least it's good to know that it's not the export that's going wrong. (In case anyone wants to test this package out too, make sure to name your export `units`)
