### ISSUE TITLE
merge-layers incorrectly converts a MultiPolygon into a Polygon

### ISSUE THREAD

**Issue by eric-g-97477** [mbloch/mapshaper#582]
I issued the command:

> mapshaper -i test.json,ATA.json combine-files -merge-layers target=test,ATA flatten -o merged.geo.json

and when I viewed the output in merged.geo.json, the MultiPolygon in ATA.json had been converted into a Polygon with a hole.

ATA.json contains two drawable polygons without holes.

Will try to attach the sample files.

I am using 0.6.27

**Comment by eric-g-97477** [comment]
[ATA.json.txt](https://github.com/mbloch/mapshaper/files/11298132/ATA.json.txt)
[merged.geo.json.txt](https://github.com/mbloch/mapshaper/files/11298133/merged.geo.json.txt)
[test.json.txt](https://github.com/mbloch/mapshaper/files/11298134/test.json.txt)

I needed to append the .txt extension otherwise GitHub rejects files with .json

**Comment by mbloch** [comment]
It looks to me that the multipolygon containing two adjacent rings was merged by mapshaper into a simple polygon without a hole.

The multipolygon has invalid geometry, according to common rules for polygon geometry in GIS. Here is one reference: https://postgis.net/workshops/postgis-intro/validity.html. The rule in question is "Rings may not touch other rings, except at a point."

Because you used the `flatten` option, mapshaper tried to repair the geometry. The result is similar to running mapshaper's `-clean` command. If you don't want mapshaper to do this kind of repair, you can split the multipolygon into simple polygons using the `-explode` command, or just leave off the `flatten` option.

**Comment by eric-g-97477** [comment]
Ah. Thank you for the reference. It was helpful. In this case, I just changed the geometry so they would be unnoticably close, but would not touch. mapshaper was then able to successfully do the merge.

```
"geometry": {
        "coordinates": [
          [
            [
              [
                -180,
                -89.999999
              ],
              [
                -180,
                -62
              ],
              [
                -0.000001,
                -62
              ],
              [
                -0.000001,
                -89.999999
              ],
              [
                -180,
                -89.999999
              ]
            ]
          ],
          [
            [
              [
                179.999999,
                -89.999999
              ],
              [
                179.999999,
                -62
              ],
              [
                0,
                -62
              ],
              [
                0,
                -89.999999
              ],
              [
                179.999999,
                -89.999999
              ]
            ]
          ]
        ],
```
