### ISSUE TITLE
Export to GeoJSON failed for an unknown reason

### ISSUE THREAD

**Issue by hsinyucindy** [mbloch/mapshaper#590]
As of this morning, I am unable to export in GeoJSON format from mapshaper.org. Error is always the same: Export failed for an unknown reason. Exporting as TopJSON and TopoJSON also seemed not to work.

**Comment by mbloch** [comment]
I was able to export GeoJSON and TopoJSON using several different datasets. The problem may be related to your dataset or your web browser. Can you provide a sample dataset that causes this problem, and also tell me your web browser, operating system, and browser version?

**Comment by hsinyucindy** [comment]
Dataset was download from https://data.gov.tw/dataset/7441
I have tried on latest version of both Chrome on window and Safari on Mac, so problems may be caused by dataset.
Thanks!

**Comment by mbloch** [comment]
I see the problem... mapshaper doesn't know how to interpret the `.prj` file from the original Shapefile. I will look into how to handle this kind of Shapefile correctly. Meanwhile, you can import the Shapefile without the `.prj` file by dragging the other component files onto `mapshaper.org`. Mapshaper will assign the default CRS, which is WGS84. If you are combining this data with other datasets, there may be a small offset, due to mapshaper's inability to read the `.prj` file (i'm not sure).

**Comment by mbloch** [comment]
I updated mapshaper to be able to import the `.prj` file from the failing Shapefile. I think this issue can be closed now.
