### ISSUE TITLE
snap option removed from import tab on web version

### ISSUE THREAD

**Issue by jucardwell** [mbloch/mapshaper#593]
Hi, 

Several weeks ago, I used the web version for snapping dangles and misses on a road network dataset. On the import tab, there was a checkbox option to execute that. That feature seems to have been removed. I am wondering what exact arguments were included in that tool, so that I could re-create it in the console. I've tried several options and haven't been able to re-create it. 

Thanks

**Comment by mbloch** [comment]
Hi! I took off the "snap" checkbox because snapping with a default distance threshold is not a very reliable way to fix topological errors, and because it is just one of many import options that are available as a command line option. You can still use the "snap" option by adding it to the command line options field, as shown below: 
![image](https://github.com/mbloch/mapshaper/assets/1232222/56ef7aa0-7c9f-44f4-9a4c-bf2b24aba38f)

I also added "snap" to the options tooltip, and I also added a click action, for viewing all of the import options:

![image](https://github.com/mbloch/mapshaper/assets/1232222/161d8e41-270e-4e26-a77e-8e9dddb7f38d)

Hope this helps!

**Comment by jucardwell** [comment]
Got it, thanks
