### ISSUE TITLE
intersections no longer highlighted

### ISSUE THREAD

**Issue by adisidev** [mbloch/mapshaper#653]
In the past, when our map had intersections, it would highlight the intersection points in red. However, I can't figure out how to enable this again.

This was a really helpful feature, is there any way I can enable it again?

**Comment by mbloch** [comment]
![image](https://github.com/user-attachments/assets/7cebe8a2-7bf4-4fb0-97e7-782f87f8280e)

You should see a link to check for intersections when viewing a polyline or polygon data layer. I switched intersection checking to on-demand only because it can be slow on large datasets. Users shouldn't have to wait for intersection checking to finish if it's not important to them.

It looks like the little red intersection dots are not displaying currently, I'll get that fixed (there should be two dots in the image below).

![image](https://github.com/user-attachments/assets/1e290428-e1ec-4f24-89cb-e6926c5efda6)

**Comment by mbloch** [comment]
The intersection dots should be fixed now
![image](https://github.com/user-attachments/assets/dc63848b-65a7-4b7c-8673-0ec66730de5e)

**Comment by adisidev** [comment]
Yep, I agree with your philosophy about making intersection checking on demand. I was indeed talking about the red dots not showing up. Just confirmed, that's been fixed on my side too, thank you so much!

On a side note, I had a quick question: what kind of map have you plotted in the earlier image you posted (the one that doesn't have the red dots highlighted)? I'm curious how you were able to get the blue lines to show / what they represent.
