### ISSUE TITLE
BUG: Nodes Disappearing After Downloading Without Modification

### ISSUE THREAD

**Issue by ViniciusCestarii** [mbloch/mapshaper#655]
I encountered an issue with Mapshaper where nodes in my GeoJSON file disappear after uploading and downloading the file without making any modifications. This behavior is unexpected, as I did not alter the file during the process.

Steps to Reproduce:

Upload a GeoJSON file to Mapshaper.
Download the GeoJSON file without making any changes.
Compare the downloaded file with the original file.

Expected Behavior:

The downloaded GeoJSON file should match the original file exactly, with all nodes and features intact.

Actual Behavior:

Some nodes and features are missing in the downloaded GeoJSON file. This issue persists even though no modifications were made to the file during the process.

GeoJSON File:

https://github.com/dadosfera/brasil-municipios-geojson/blob/main/geojs-100-mun-v2.json

Before:

![image](https://github.com/user-attachments/assets/d1b06eb1-4ed9-4572-9f25-fd28a302d1d5)

After:

![image](https://github.com/user-attachments/assets/14ec0ef4-8b6c-4dfb-945e-4b19e23fc883)

I highlighted these two nodes which have disappeared, but there are additional nodes affected as well.

![image](https://github.com/user-attachments/assets/2fcd3076-14cf-40ef-8fa3-e8224c6bd0e9)

**Comment by mbloch** [comment]
Thanks for reporting this :)

I extracted one of the disappearing shapes for testing, here's a link to the sample file and an image of the shape in mapshaper:
[extract.json](https://github.com/user-attachments/files/16885096/extract.json)

![image](https://github.com/user-attachments/assets/9b85c57f-e3ff-4ff1-9fd8-2c50f21d1cf8)

The example shape consists of two polygon rings. This kind of shape should be represented as a `MultiPolygon` in GeoJSON, but if you look at the file, you'll see that the geometry type is `Polygon`, with two coordinate rings. According to the GeoJSON spec, when a `Polygon` contains multiple rings, the first ring in the array is an exterior ring and the following rings are holes. When mapshaper exports the file, it sees that the "hole" is not actually contained by the exterior ring and deletes it. The shapes are disappearing because they are not valid GeoJSON polygons.

You can fix the problem in mapshaper by running the console command: `-clean rewind`.

Mapshaper should give you some kind of warning about the problem, instead of just silently deleting rings...  this kind of invalid geometry appears so rarely that I didn't think to add a warning, but I will put it on my TODO list. 

--Matt
