### ISSUE TITLE
Document projection command

### ISSUE THREAD

**Issue by gka** [mbloch/mapshaper#92]
Where can I find help on the project command? Seems this is not listed in `mapshaper -help`.

**Comment by mbloch** [comment]
I didn't document the -proj command because it's not quite ready for general use... I guess I could document it and add a warning about its limitations. 

The main limitations are:
* Polygons and polylines do not get clipped when they intersect the limits of a projection.
* Only a few projections are implemented -- Albers Conformal Conic, Lambert Conformal Conic, Mercator, Robinson, Winkel Tripel, Transverse Mercator (and UTM), and "albersnyt" (you can type -projections to see the list).
* There should probably be a densification command, or maybe even automatic densification, in case a straight line in an unprojected dataset (e.g. a graticule line) needs to get projected to a curved line but doesn't have enough internal vertices to approximate a curve.

**Comment by gipong** [comment]
Is it possible to deal with projection by integrating Proj4js Library?

**Comment by mbloch** [comment]
I don't want to add projection as a documented feature until mapshaper supports a few other related operations: clipping shapes along projection boundaries, densification, and merging polygons that have been split across the antemeridian.

If you're interested in forking mapshaper to add proj4js support, there is an undocumented `-proj` command, i think it wouldn't be hard to replace the current implementation with proj4js.

**Comment by mbloch** [comment]
I just released a new version of mapshaper with support for reprojection. I also added the `-proj` and `-projections` commands to wiki and to mapshaper's `-help` command.

I haven't implemented polygon clipping yet... eventually I hope to have something similar to d3's geo projections, with support for interrupted projections and polygon splicing.

**Comment by mbloch** [comment]
Now that [-proj] is documented in the wiki and in command line help, this issue can be closed.
