### ISSUE TITLE
Use applyCommands on two objects (eg., with clip, erase, etc)

### ISSUE THREAD

**Issue by ateucher** [mbloch/mapshaper#95]
First, thank you so much for mapshaper. The topologically-aware polygon simplification is superb; it saves me on a regular basis.

I apologize if this is documented somewhere already, but I'm trying to use `mapshaper.applyCommands` to clip a GeoJSON object on another GeoJSON object.

In the node REPL:

``` javascript
var mapshaper = require('mapshaper');

var poly = {
  "type": "Feature",
  "geometry": {
  "type": "Polygon",
  "coordinates": [
  [
  [-114.345703125, 39.4369879],
  [-116.4534998, 37.18979823791],
  [-118.4534998, 38.17698709],
  [-115.345703125, 43.576878],
  [-106.611328125, 43.4529188935547],
  [-105.092834092, 46.20938402],
  [-106.66859, 39.4389646],
  [-103.6117867, 36.436756],
  [-114.34579879, 39.4361929]
  ] ]
  }
}

var clip_poly = {
  "type": "Feature",
  "geometry": {
  "type": "Polygon",
  "coordinates": [
  [
  [-114.345703125, 39.4361929993141],
  [-114.345703125, 43.4529188935547],
  [-106.611328125, 43.4529188935547],
  [-106.611328125, 39.4361929993141],
  [-114.345703125, 39.4361929993141]
  ] ]
  }
}

mapshaper.applyCommands("-clip clip_poly", poly, function(Error, data) {
  if (Error) console.error(Error);
  console.log(data);
})
```

I get: `APIError: File not found (clip_poly)`. 

 Is there a way to specify the clipping layer as an object rather than a filename with `applyCommands`?

**Comment by ateucher** [comment]
For context, I am trying to write an [R package](https://github.com/ateucher/rmapshaper) that wraps `mapshaper`, using the V8 engine.

**Comment by mbloch** [comment]
Hi, thanks for filing this.

Your question points to a limitation in Mapshaper's  applyCommands() function: it's not designed to accept more than one GeoJSON dataset as input. To clip one GeoJSON dataset with a second one, the second set of shapes must be contained in a file, not a JS object. That's why you're getting a "File not found" error: the `-clip` command expects a filename, not the name of a variable.

I'd like to update Mapshaper's JS api and its command line tool to work more like the web UI, which is able to import multiple datasets and perform commands like `clip` and `join` between them. I'll consider your use case as I work on the update.

**Comment by ateucher** [comment]
Thanks very much for that, it's what I figured. I think I should be able to dig deeper and access it more directly (possibly via `runCommand`) for now, but look forward to updates in the future!

Thanks again

**Comment by dossy** [comment]
+1, just wanted to say I'd like to see this implemented, as well.

**Comment by mbloch** [comment]
Finally, there is a solution for using `applyCommands()` with multiple input datasets. 

There is a new way to call `applyCommands()` (the old way is deprecated but continues to function). 

As the second argument, you can pass a JS object containing input datasets indexed by filename.

To access an input file, you reference it in a `-i` command using its filename, just as if you were reading the file from disk.

Output files are returned as the second argument in a Node-style callback, using the same format as your input files (in an object, indexed by filename).

For example:
```
// converts a CSV file to JSON records
require('mapshaper').applyCommands(
    '-i input.csv -o output.json format=json',
    {'input.csv': <csv>},
     function(err, output) {
	// output is {'output.json': <json>}
    });

```

**Comment by ateucher** [comment]
Fantastic! Will give it a go soon. Thanks so much.

**Comment by atoiv** [comment]
This issue seems to be closed after the january v0.4.0 release,  but I was wondering whether or not the original `-clip` example from this issue's initial post would still be possible using `applyCommands` and maps passed as js objects?

e.g. if i want to do the following:

```javascript
const input = {
  'original.json': { /*...*/ },
  'clip.json': { /*...*/ },
};

mapshaper.applyCommands(
    `-i original.json -clip clip.json`,
    input,
    (error, output) => { /*...*/ }
);
```

I still get the error `APIError: [clip] File not found (clip.json)`, as in the original post. The other file (original.json) used with `-i` seems to be found correctly.

I tried to look at the source, but `applyCommands` in [`src/cli/mapshaper-commands.js`](https://github.com/mbloch/mapshaper/blob/master/src/cli/mapshaper-commands.js) seems to only read files flagged with either `-i` or `-join` to be read from `input` parameter.

**Comment by mbloch** [comment]
Thanks for catching this!

I'll try to come up with a better solution for caching input datasets than adding an "input" parameter to certain commands. Meanwhile, I've published v0.4.40, which adds support for -clip and -erase.

**Comment by atoiv** [comment]
Thanks, that was a fast fix! 😀 

Great work with mapshaper, it's a super handy tool.

**Comment by brambow** [comment]
Very happy to see this improvement, but I'm having trouble with clip + applyCommand.  No error, but I'm just getting an empty object.  Any advice on what I'm doing wrong would be appreciated - same datasets work in command line:

`        const arg = 'inputLayer -clip clipLayer';
          const input = {
            "inputLayer": map.sources[inputLyr.source].data,  //geojson feature collection
            "clipLayer": map.sources[clipLyr.source].data  //geojson feature collection
          };

          mapshaper.applyCommands(arg, input, function(err, output) {
            if(err) console.log(err);
            console.log(output);
          })

`
