### ISSUE TITLE
"RangeError: Invalid string length" when exporting GeoJSON

### ISSUE THREAD

**Issue by jlev** [mbloch/mapshaper#97]
Hi, I'm trying to use mapshaper to convert TIGER shapefiles of ZCTAs to geojson, and split the result up by state. I'm joining the tl_2012_us_zcta510.shp with the Census ZCTA county relation, in order to get state and county FIPS codes in the resulting file.

Running `mapshaper raw/tl_2012_us_zcta510.shp -join raw/zcta_county_rel_10.txt keys="GEOID10,ZCTA5:str" fields="ZCTA5:str,STATE:str,COUNTY:str" -filter-fields "ZCTA5,STATE,COUNTY" -o format=geojson`, I get 

```/usr/local/lib/node_modules/mapshaper/mapshaper.js:1458
    throw err;
          ^
RangeError: Invalid string length
    at /usr/local/lib/node_modules/mapshaper/mapshaper.js:8392:17
    at Array.reduce (native)
    at Object.MapShaper.exportGeoJSONString (/usr/local/lib/node_modules/mapshaper/mapshaper.js:8376:28)
    at /usr/local/lib/node_modules/mapshaper/mapshaper.js:8276:26
    at Array.map (native)
    at MapShaper.exportGeoJSON (/usr/local/lib/node_modules/mapshaper/mapshaper.js:8274:25)
    at Object.MapShaper.exportFileContent (/usr/local/lib/node_modules/mapshaper/mapshaper.js:9933:11)
    at Object.api.exportFiles (/usr/local/lib/node_modules/mapshaper/mapshaper.js:11028:27)
    at Object.api.runCommand (/usr/local/lib/node_modules/mapshaper/mapshaper.js:13849:11)
    at /usr/local/lib/node_modules/mapshaper/mapshaper.js:15310:9
```

I suspect the problem is with the join, and maybe the fact that the shapefile includes features that aren't in the relation. `[join] 24/33144 target records received no data`

I've tried adding a filter "remove-empty" as well as "$.isNull==false", and "$.id!==undefined", but none prunes any objects that might have null geometry. Is there any other way to skip the missing records in the export?

Alternatively, does anyone know where I can get current ZCTAs as json for the whole US? I'd like to split by state to keep file sizes small, because I'll load them only on higher zoom levels in my D3 map.

Thanks,
- Josh

**Comment by jlev** [comment]
Upon further review, the issue may not be with the join at all, but with the base shapefile. A simpler `mapshaper raw/tl_2012_us_zcta510.shp  -filter-fields="GEOID10" -filter remove-empty "$.properties.GEOID10!==undefined" -o format=geojson` produces the same error. Are there other ways of dropping empty features I should try?

**Comment by mbloch** [comment]
I think the problem here is that Node's v8 JavaScript engine is unable to generate a large enough string to contain the entire output file. (It seems to hit a limit somewhere above 500MB on my computer).

Here's an issue from a different project that discusses the same runtime error that you encountered: https://github.com/atom/atom/issues/7417

One way to solve this would be for mapshaper to stream the output GeoJSON to a file, instead of generating one huge string in memory before writing the file. This would take a bit of work on my end, I won't be able to get to it for a little while.

If you don't mind simplifying the file's geometry a bit, you could try inserting a `-simplify 15%` command before the output command -- that should also do the trick.

**Comment by jlev** [comment]
Thanks @mbloch, that will do the trick. I used mapshaper to split each state into a separate file, and then topojson to convert and simplify further, so each file ends up under a megabyte. Makefiles and output are up at storiesofsolidarity/us-data.

Thanks for the excellent tools!
